apiVersion: v1
kind: Pod
metadata:
  name: nginx-jenkins
  labels: 
    version : v1
    owner: 1tacticalretard
spec:
  containers:
  - name: container-nginx-custompage
    image: 1tacticalretard/nginx_custompage:latest
    ports: 
      - containerPort: 80
  - name: container-jenkins
    image: jenkins/jenkins:lts-jdk11
    ports: 
      - containerPort: 8080
